In [204]:
import numpy as np
import scipy as sp

In [112]:
1 / 2.0

0.5

In [ ]:
( qchisq(0.025, 2*x)/2, qchisq(0.975, 2*(x+1))/2 )

In [240]:
X = 1
sigma = 2
conf = 0.95
a1 = (1 - conf) / 2.0
a2 = 1 - a1
sp.stats.chi2.ppf(a1, 2 * X) / 2, sp.stats.chi2.ppf(a2, 2 * (X + 1)) / 2

(0.025317807984289876, 5.5716433909388972)

In [196]:
from scipy import interpolate

In [243]:
CONF_INT = np.linspace(0, 1, 1000)
mu = 1
vals = sp.stats.chi2.ppf((1 - CONF_INT) / 2.0, 2 * mu) / 2
FFS = interpolate.interp1d(vals, CONF_INT)
conf = FFS(0.02)
conf
np.interp(conf, sigma_to_conf, sigma_interval)

2.057871752536534

<h1> need to reverse the above code </h1>

In [ ]:
CONF_INT = np.linspace(0, 1, 1000)
def get_poisson_sigma(mu, val):
    if val < mu:
        vals = spy.stats.chi2.ppf(((1 - CONF_INT) / 2.0), 2 * mu) / 2
        FFS = interpolate.interp1d(vals, CONF_INT)
        conf = FFS(0.2)
        conf = FFS(0.2)
        np.interp(conf, sigma_to_conf, sigma_interval)
        

In [140]:
np.array(stats.chi2.interval(.95, 6 * 2)) / 2.0 + [0, 1]


array([  2.20189425,  12.66833208])

In [108]:
cdf_diff = np.diff(scipy.stats.poisson.cdf([3, 8.8], 3))
cdf_diff * 2

array([ 0.69793024])

In [106]:
1 - (cdf_diff - 0.5) / 2

array([ 1.07551744])

In [109]:
conf_int = 1 - (0.5-cdf_diff)*2
#conf_int = 1 - (cdf_diff - 0.5) / 2

<h1> compute n sigma from effective confidence interval (area on one side) </h1>

In [110]:
print conf_int
np.interp(conf_int, sigma_to_conf, sigma_interval)

[ 0.69793024]


array([ 1.03200872])

In [46]:
sp.special.erf(1/np.sqrt(2))

0.68268949213708585

In [70]:
sigma_interval = np.linspace(0,8,1000)
sigma_to_conf = scipy.special.erf(sigma_interval / np.sqrt(2))

In [71]:
sigma_to_conf

array([ 0.        ,  0.0063894 ,  0.01277839,  0.01916655,  0.02555349,
        0.0319388 ,  0.03832205,  0.04470285,  0.05108078,  0.05745545,
        0.06382643,  0.07019334,  0.07655575,  0.08291327,  0.08926549,
        0.09561201,  0.10195242,  0.10828634,  0.11461335,  0.12093307,
        0.12724509,  0.13354902,  0.13984446,  0.14613103,  0.15240834,
        0.15867599,  0.1649336 ,  0.17118079,  0.17741716,  0.18364236,
        0.18985598,  0.19605766,  0.20224703,  0.20842371,  0.21458733,
        0.22073752,  0.22687393,  0.23299619,  0.23910393,  0.24519682,
        0.25127448,  0.25733657,  0.26338275,  0.26941266,  0.27542597,
        0.28142233,  0.28740142,  0.29336289,  0.29930643,  0.30523169,
        0.31113837,  0.31702614,  0.32289468,  0.32874369,  0.33457285,
        0.34038186,  0.34617042,  0.35193822,  0.35768499,  0.36341041,
        0.36911422,  0.37479612,  0.38045584,  0.3860931 ,  0.39170763,
        0.39729917,  0.40286745,  0.40841221,  0.4139332 ,  0.41

In [75]:
np.interp(np.array([0.997]), sigma_to_conf, sigma_interval)

array([ 2.96776081])

In [162]:
sigma_to_conf

array([ 0.        ,  0.0063894 ,  0.01277839,  0.01916655,  0.02555349,
        0.0319388 ,  0.03832205,  0.04470285,  0.05108078,  0.05745545,
        0.06382643,  0.07019334,  0.07655575,  0.08291327,  0.08926549,
        0.09561201,  0.10195242,  0.10828634,  0.11461335,  0.12093307,
        0.12724509,  0.13354902,  0.13984446,  0.14613103,  0.15240834,
        0.15867599,  0.1649336 ,  0.17118079,  0.17741716,  0.18364236,
        0.18985598,  0.19605766,  0.20224703,  0.20842371,  0.21458733,
        0.22073752,  0.22687393,  0.23299619,  0.23910393,  0.24519682,
        0.25127448,  0.25733657,  0.26338275,  0.26941266,  0.27542597,
        0.28142233,  0.28740142,  0.29336289,  0.29930643,  0.30523169,
        0.31113837,  0.31702614,  0.32289468,  0.32874369,  0.33457285,
        0.34038186,  0.34617042,  0.35193822,  0.35768499,  0.36341041,
        0.36911422,  0.37479612,  0.38045584,  0.3860931 ,  0.39170763,
        0.39729917,  0.40286745,  0.40841221,  0.4139332 ,  0.41